# Generated by Django 4.2.1 on 2023-05-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhongKhamTu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dangky',
            name='gioitinh',
            field=models.CharField(choices=[('nam', 'NAM'), ('nu', 'NU')], default='nam', max_length=10),
        ),
    ]
