# Generated by Django 4.2.1 on 2023-05-13 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PhongKhamTu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toathuoc',
            name='cach_dung',
        ),
    ]
